name: event
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  skeletonizer: ^1.4.2
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  easy_container: ^1.0.5
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  intl: ^0.17.0
  random_string: ^2.3.1
  delayed_display: ^2.0.0
  shared_preferences: ^2.5.2
  flutter_colorpicker: ^1.1.0
  http: ^1.0.0
  flutter_animate: ^4.5.2
  webview_flutter: ^4.11.0
  razorpay_flutter: ^1.4.0
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/banner/
    - assets/event/
    - assets/images/
    - assets/profileImg/
    - assets/searchImg/
    - assets/auth/
    - assets/logo/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/eventhub.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/eventhub.jpg"
